export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const INCREMENT_COUNTER2 = "INCREMENT_COUNTER2";
export const DECREMENT_COUNTER2 = "DECREMENT_COUNTER2";

export const INCREMENT_COUNTER_ASYNC = "INCREMENT_COUNTER_ASYNC";
export const DECREMENT_COUNTER_ASYNC = "DECREMENT_COUNTER_ASYNC";

export const SHOW_PRODUCT_VALUE = "SHOW_PRODUCT_VALUE";
